## Matrix Decomposition Exercise

In [42]:
# import numpy
import numpy as np

**Task:** Generate a random matrix 'A' with a shape of 150x50, using the '**np.random.rand**' function.

In [2]:
A = np.random.rand(150,50)

**Task:** Check the shape of 'A'.

In [3]:
A.shape

(150, 50)

**Task:** Decompose matrix 'A' with SVD using numpy (decompose into matrices U,D,V).

In [4]:
U, D, V = np.linalg.svd(A)

**Task:** Check the shapes of matrices U,D,V.

In [6]:
print(U.shape)
print(D.shape)
print(V.shape)

(150, 150)
(50,)
(50, 50)


**Task:** Reconstruct matrix 'A' from matrices U,D,V.

In [45]:
# Equation from Kelvin the mentor
A_2 = U[:, :50].dot(np.diag(D)).dot(V)
A_2

array([[0.60036684, 0.42109987, 0.48224292, ..., 0.19726243, 0.90204028,
        0.94189901],
       [0.67826333, 0.31711569, 0.34495824, ..., 0.92173436, 0.29315768,
        0.52290771],
       [0.84478745, 0.13364234, 0.34800968, ..., 0.11873989, 0.92980144,
        0.77734481],
       ...,
       [0.24597399, 0.52377133, 0.73234502, ..., 0.09512227, 0.96883619,
        0.00766182],
       [0.27483228, 0.70581892, 0.88384601, ..., 0.19190517, 0.00288347,
        0.97080075],
       [0.10938738, 0.11240134, 0.19119481, ..., 0.70340972, 0.46310973,
        0.71304324]])

In [44]:
# Equation from Compass walkthrough  https://data.compass.lighthouselabs.ca/activities/493
reconst = np.matrix(U[:,:50]) * np.diag(D) * np.matrix(V[:,:])
reconst

matrix([[0.60036684, 0.42109987, 0.48224292, ..., 0.19726243, 0.90204028,
         0.94189901],
        [0.67826333, 0.31711569, 0.34495824, ..., 0.92173436, 0.29315768,
         0.52290771],
        [0.84478745, 0.13364234, 0.34800968, ..., 0.11873989, 0.92980144,
         0.77734481],
        ...,
        [0.24597399, 0.52377133, 0.73234502, ..., 0.09512227, 0.96883619,
         0.00766182],
        [0.27483228, 0.70581892, 0.88384601, ..., 0.19190517, 0.00288347,
         0.97080075],
        [0.10938738, 0.11240134, 0.19119481, ..., 0.70340972, 0.46310973,
         0.71304324]])

**Task:** Compare matrices 'A' and 'A_rec' with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

In [46]:
np.allclose(A,reconst)

True

In [33]:
np.allclose(A,A_2)

True

**Task:** Reduce the dimnesion of matrix 'A' to shape 150x20 with SVD (try both equations).

In [56]:
A3 = U[:, :20].dot(np.diag(D[:20])).dot(V[:20])
A3.shape

(150, 50)

In [60]:
A_rec = np.matrix(U[:,:20]) * np.diag(D[:20]) * np.matrix(V[:20])

**Task:** Print the shape.

In [61]:
A3.shape

(150, 50)

In [63]:
A_rec.shape

(150, 50)

**Task:** Compare the two results with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

In [64]:
np.allclose(A,A3)

False

In [65]:
np.allclose(A,A_rec)

False

**Task:** Filter the noise from matrix 'A' with 20 largest singular vectors (keep the shape of (150x50)).

In [77]:
Af1 = U[:,:20].dot(np.diag(D[:20])).dot(V[:20])
Af1.shape

(150, 50)

In [78]:
Af2 = np.matrix(U[:, :20]) * np.diag(D[:20]) * np.matrix(V[:20])
Af2.shape

(150, 50)

**Task:** Check the shape.

**Task:** Define the function `'SVD'` which perform singular values decomposition.

Do not forget to hceck the shape of the input matrix.

In [79]:
def SVD(A):
    """
    PARAMS:
        A (numpy.ndarray) - matrix to decompose
    RETURN:
        U (numpy.ndarray) - left singular vectors
        SV (numpy.ndarray) - singular values
        V (numpy.ndarray) - right singular vectors
    """
    U, SV, V = np.linalg.svd(A)
    return U, SV, V

**Task:** Call the function `'SVD'` on matrix 'A'.

In [80]:
SVD(A)

(array([[-8.04515620e-02, -5.93338199e-02, -6.21132559e-02, ...,
         -2.08460298e-02, -4.24256932e-02, -7.10532202e-03],
        [-8.50570178e-02,  1.16186515e-01,  2.59067549e-02, ...,
          1.37991284e-02,  8.78444101e-02, -3.56476389e-02],
        [-8.09562272e-02,  1.36392360e-01, -1.97835168e-01, ...,
         -5.30320684e-02,  2.64196444e-02,  2.35936191e-01],
        ...,
        [-7.49088511e-02, -2.09752779e-03, -1.36811235e-01, ...,
          6.96496079e-01,  1.85169643e-02,  4.01221375e-02],
        [-9.03481643e-02,  1.51438510e-01,  7.10206747e-02, ...,
         -1.00619832e-02,  6.31048410e-01, -4.36698132e-02],
        [-8.24629192e-02, -1.35151971e-01, -9.76080475e-02, ...,
         -9.65515987e-03, -6.62582667e-04,  6.91406125e-01]]),
 array([43.76323463,  5.28617962,  5.21561189,  5.00401543,  4.91741709,
         4.75827784,  4.73961117,  4.66870209,  4.53321161,  4.45154816,
         4.40631536,  4.24802043,  4.22609215,  4.1875968 ,  4.08630897,
         4